SELECT COLUNAS.NAME AS COLUNA, TIPOS.NAME AS TIPO, COLUNAS.LENGTH AS TAMANHO, COLUNAS.ISNULLABLE AS NULOS
FROM SYSOBJECTS AS TABELAS, SYSCOLUMNS AS COLUNAS, SYSTYPES   AS TIPOS
WHERE TABELAS.ID = COLUNAS.ID AND COLUNAS.USERTYPE = TIPOS.USERTYPE AND (TABELAS.NAME = '[TABELA]' OR TABELAS.NAME = '[TABELA]')
